/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SistemaAgendaElectronica.GUI;

import SistemaAgendaElectronica.BD.Contactos;
import SistemaAgendaElectronica.BD.Usuarios;
import SistemaAgendaElectronica.Servicios.Encriptado;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    private String dato;

    public Ventana2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setDato(String dato) {
        this.dato = dato;
        txtEnvioDeUsuario.setText(dato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtEnvioDeUsuario = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtAgregarLocalidad = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnAgregarContacto = new javax.swing.JButton();
        txtAgregarApellido = new javax.swing.JTextField();
        txtAgregarDni = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginBtn8 = new javax.swing.JLabel();
        txtAgregarNombre = new javax.swing.JTextField();
        txtAgregarDireccion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnConsultarContacto = new javax.swing.JButton();
        txtConsultarNombre = new javax.swing.JTextField();
        txtConsultarDni = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPantallaDeContactos = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnModificarContacto1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        TxtEnviarContactoModificado = new javax.swing.JTextField();
        txtModificarNombre1 = new javax.swing.JTextField();
        txtModificarDni1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtModificarDireccion1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtModificarApellido1 = new javax.swing.JTextField();
        txtModificarLocalidad1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnEliminarContacto2 = new javax.swing.JButton();
        txtPantallaDeContactos3 = new javax.swing.JTextField();
        txtEliminarNombre2 = new javax.swing.JTextField();
        txtEliminarDni1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        txtEnvioDeUsuario.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        txtEnvioDeUsuario.setForeground(new java.awt.Color(0, 204, 204));
        txtEnvioDeUsuario.setText("...........................................");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("HOLA! ");

        jLabel25.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 204, 204));
        jLabel25.setText("DIRECCIÓN");

        txtAgregarLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarLocalidadActionPerformed(evt);
            }
        });
        txtAgregarLocalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgregarLocalidadKeyReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 204, 204));
        jLabel27.setText("LOCALIDAD");

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 204, 204));
        jLabel28.setText("NOMBRE");

        jLabel29.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 204, 204));
        jLabel29.setText("DNI");

        btnAgregarContacto.setBackground(new java.awt.Color(102, 102, 255));
        btnAgregarContacto.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnAgregarContacto.setText("AGREGAR CONTACTO");
        btnAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContactoActionPerformed(evt);
            }
        });

        txtAgregarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarApellidoActionPerformed(evt);
            }
        });
        txtAgregarApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgregarApellidoKeyReleased(evt);
            }
        });

        txtAgregarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarDniActionPerformed(evt);
            }
        });
        txtAgregarDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgregarDniKeyReleased(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 204, 204));
        jLabel30.setText("APELLIDO");

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N

        loginBtn8.setBackground(new java.awt.Color(255, 102, 204));
        loginBtn8.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        loginBtn8.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn8.setText("☕");
        loginBtn8.setToolTipText("");
        loginBtn8.setPreferredSize(new java.awt.Dimension(50, 50));
        loginBtn8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginBtn8FocusGained(evt);
            }
        });
        loginBtn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtn8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtn8MouseReleased(evt);
            }
        });

        txtAgregarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgregarNombreKeyReleased(evt);
            }
        });

        txtAgregarDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgregarDireccionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel29))
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAgregarApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(txtAgregarDni))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(loginBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel28))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAgregarDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addContainerGap(22, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnvioDeUsuario)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel27)
                                .addGap(20, 20, 20)
                                .addComponent(txtAgregarLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(142, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnvioDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtAgregarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtAgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgregarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgregarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgregarLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAgregarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AGREGAR", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("DNI");

        btnConsultarContacto.setBackground(new java.awt.Color(102, 102, 255));
        btnConsultarContacto.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnConsultarContacto.setText("CONSULTAR CONTACTO");
        btnConsultarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarContactoActionPerformed(evt);
            }
        });

        txtConsultarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultarNombreKeyReleased(evt);
            }
        });

        txtConsultarDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultarDniKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setText("NOMBRE");

        txtPantallaDeContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaDeContactosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtConsultarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnConsultarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtPantallaDeContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConsultarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConsultarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnConsultarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtPantallaDeContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTAR", jPanel2);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        jLabel33.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 204, 204));
        jLabel33.setText("LOCALIDAD");

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 204, 204));
        jLabel34.setText("NOMBRE");

        btnModificarContacto1.setBackground(new java.awt.Color(102, 102, 255));
        btnModificarContacto1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnModificarContacto1.setText("MODIFICAR CONTACTO");
        btnModificarContacto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarContacto1ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 204, 204));
        jLabel35.setText("INGRESE DNI DEL CONTACTO");

        TxtEnviarContactoModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEnviarContactoModificadoActionPerformed(evt);
            }
        });
        TxtEnviarContactoModificado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEnviarContactoModificadoKeyReleased(evt);
            }
        });

        txtModificarDni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarDni1ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 204, 204));
        jLabel36.setText("APELLIDO");

        jLabel37.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 204, 204));
        jLabel37.setText("DIRECCIÓN");

        jLabel40.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 204, 204));
        jLabel40.setText("DNI");

        txtModificarApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarApellido1ActionPerformed(evt);
            }
        });
        txtModificarApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModificarApellido1KeyReleased(evt);
            }
        });

        txtModificarLocalidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarLocalidad1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModificarDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificarLocalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel36)
                        .addGap(48, 48, 48)
                        .addComponent(txtModificarApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnModificarContacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel34)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtModificarNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(txtModificarDni1)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel35)
                            .addGap(18, 18, 18)
                            .addComponent(TxtEnviarContactoModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificarDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificarLocalidad1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModificarApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarContacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(TxtEnviarContactoModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtModificarDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModificarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(217, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("MODIFICAR", jPanel4);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        btnEliminarContacto2.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminarContacto2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnEliminarContacto2.setText("ELIMINAR CONTACTO");
        btnEliminarContacto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContacto2ActionPerformed(evt);
            }
        });

        txtPantallaDeContactos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaDeContactos3ActionPerformed(evt);
            }
        });

        txtEliminarNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEliminarNombre2KeyReleased(evt);
            }
        });

        txtEliminarDni1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEliminarDni1KeyReleased(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 204, 204));
        jLabel39.setText("NOMBRE");

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("DNI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel39))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEliminarDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEliminarNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnEliminarContacto2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtPantallaDeContactos3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEliminarDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEliminarNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminarContacto2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtPantallaDeContactos3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ELIMINAR", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPantallaDeContactos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaDeContactos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaDeContactos3ActionPerformed

    private void btnEliminarContacto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContacto2ActionPerformed
        Contactos contactos = new Contactos();

        String dni = txtEliminarDni1.getText();
        String nombre = txtEliminarNombre2.getText();

        contactos.eliminarContacto(dni, nombre);

        txtEliminarDni1.setText(null);
        txtEliminarNombre2.setText(null);

    }//GEN-LAST:event_btnEliminarContacto2ActionPerformed

    private void txtModificarDni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarDni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarDni1ActionPerformed

    private void TxtEnviarContactoModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEnviarContactoModificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEnviarContactoModificadoActionPerformed

    private void btnModificarContacto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarContacto1ActionPerformed
        Contactos contactos = new Contactos();

        String dni = txtModificarDni1.getText();
        String nombre = txtModificarNombre1.getText();
        String apellido = txtModificarApellido1.getText();
        String direccion = txtModificarDireccion1.getText();
        String localidad = txtModificarLocalidad1.getText();
        String envioDniContacto = TxtEnviarContactoModificado.getText();

        contactos.modificarContacto(dni, nombre, apellido, direccion, localidad, envioDniContacto);

        txtModificarDni1.setText(null);
        txtModificarNombre1.setText(null);
        txtModificarApellido1.setText(null);
        txtModificarDireccion1.setText(null);
        txtModificarLocalidad1.setText(null);
        TxtEnviarContactoModificado.setText(null);


    }//GEN-LAST:event_btnModificarContacto1ActionPerformed

    private void txtPantallaDeContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaDeContactosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaDeContactosActionPerformed

    private void btnConsultarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarContactoActionPerformed

        Contactos contactos = new Contactos();

        String dni = txtConsultarDni.getText();
        String nombre = txtConsultarNombre.getText();

        contactos.consultarContacto(dni, nombre);

        txtConsultarDni.setText(null);
        txtConsultarNombre.setText(null);

    }//GEN-LAST:event_btnConsultarContactoActionPerformed

    private void txtAgregarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarDniActionPerformed

    private void btnAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContactoActionPerformed
        Contactos contactos = new Contactos();
        String dni = txtAgregarDni.getText();
        String nombre = txtAgregarNombre.getText();
        String apellido = txtAgregarApellido.getText();
        String direccion = txtAgregarDireccion.getText();
        String localidad = txtAgregarLocalidad.getText();

        if (contactos.verificacionDeContacto(dni, nombre, apellido, direccion, localidad)) {
            JOptionPane.showMessageDialog(null, "¡Contacto registrado exitosamente!");
        } else {
            JOptionPane.showMessageDialog(null, "Contacto no registrado");
            btnAgregarContacto.setEnabled(false);
        }

// Limpiar los campos después de agregar el contacto
        txtAgregarDni.setText(null);
        txtAgregarNombre.setText(null);
        txtAgregarApellido.setText(null);
        txtAgregarDireccion.setText(null);
        txtAgregarLocalidad.setText(null);
        
        
        

    }//GEN-LAST:event_btnAgregarContactoActionPerformed

    private void loginBtn8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginBtn8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8FocusGained

    private void loginBtn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MouseClicked

    private void loginBtn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MouseExited

    private void loginBtn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MousePressed

    private void loginBtn8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn8MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn8MouseReleased

    private void txtAgregarDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarDniKeyReleased
        if (!txtAgregarDni.getText().isEmpty()) {
            btnAgregarContacto.setEnabled(true);

        } else {
            btnAgregarContacto.setEnabled(false);
        }
    }//GEN-LAST:event_txtAgregarDniKeyReleased

    private void txtAgregarApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarApellidoKeyReleased
        if (!txtAgregarApellido.getText().isEmpty()) {
            btnAgregarContacto.setEnabled(true);

        } else {
            btnAgregarContacto.setEnabled(false);
        }
    }//GEN-LAST:event_txtAgregarApellidoKeyReleased

    private void txtAgregarLocalidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarLocalidadKeyReleased
        if (!txtAgregarLocalidad.getText().isEmpty()) {
            btnAgregarContacto.setEnabled(true);

        } else {
            btnAgregarContacto.setEnabled(false);
        }
    }//GEN-LAST:event_txtAgregarLocalidadKeyReleased

    private void txtConsultarDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarDniKeyReleased
        if (!txtConsultarDni.getText().isEmpty()) {
            btnConsultarContacto.setEnabled(true);

        } else {
            btnConsultarContacto.setEnabled(false);
        }
    }//GEN-LAST:event_txtConsultarDniKeyReleased

    private void txtConsultarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarNombreKeyReleased
        if (!txtConsultarNombre.getText().isEmpty()) {
            btnConsultarContacto.setEnabled(true);

        } else {
            btnConsultarContacto.setEnabled(false);
        }
    }//GEN-LAST:event_txtConsultarNombreKeyReleased

    private void TxtEnviarContactoModificadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEnviarContactoModificadoKeyReleased
        if (!TxtEnviarContactoModificado.getText().isEmpty()) {
            btnModificarContacto1.setEnabled(true);
        } else {
            btnModificarContacto1.setEnabled(false);

        }
    }//GEN-LAST:event_TxtEnviarContactoModificadoKeyReleased

    private void txtEliminarDni1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEliminarDni1KeyReleased
        if (!txtEliminarDni1.getText().isEmpty()) {
            btnEliminarContacto2.setEnabled(true);
        } else {
            btnEliminarContacto2.setEnabled(true);

        }
    }//GEN-LAST:event_txtEliminarDni1KeyReleased

    private void txtEliminarNombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEliminarNombre2KeyReleased
        if (!txtEliminarNombre2.getText().isEmpty()) {
            btnEliminarContacto2.setEnabled(true);
        } else {
            btnEliminarContacto2.setEnabled(true);

        }
    }//GEN-LAST:event_txtEliminarNombre2KeyReleased

    private void txtAgregarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarNombreKeyReleased
        if (!txtAgregarNombre.getText().isEmpty()) {
            btnAgregarContacto.setEnabled(true);
        } else {
            btnAgregarContacto.setEnabled(true);

        }
    }//GEN-LAST:event_txtAgregarNombreKeyReleased

    private void txtAgregarDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarDireccionKeyReleased
        if (!txtAgregarDireccion.getText().isEmpty()) {
            btnAgregarContacto.setEnabled(true);
        } else {
            btnAgregarContacto.setEnabled(true);

        }
    }//GEN-LAST:event_txtAgregarDireccionKeyReleased

    private void txtModificarApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarApellido1ActionPerformed

    private void txtModificarLocalidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarLocalidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarLocalidad1ActionPerformed

    private void txtModificarApellido1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarApellido1KeyReleased

    }//GEN-LAST:event_txtModificarApellido1KeyReleased

    private void txtAgregarLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarLocalidadActionPerformed

    private void txtAgregarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtEnviarContactoModificado;
    private javax.swing.JButton btnAgregarContacto;
    private javax.swing.JButton btnConsultarContacto;
    private javax.swing.JButton btnEliminarContacto2;
    private javax.swing.JButton btnModificarContacto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel loginBtn8;
    private javax.swing.JTextField txtAgregarApellido;
    private javax.swing.JTextField txtAgregarDireccion;
    private javax.swing.JTextField txtAgregarDni;
    private javax.swing.JTextField txtAgregarLocalidad;
    private javax.swing.JTextField txtAgregarNombre;
    private javax.swing.JTextField txtConsultarDni;
    private javax.swing.JTextField txtConsultarNombre;
    private javax.swing.JTextField txtEliminarDni1;
    private javax.swing.JTextField txtEliminarNombre2;
    private javax.swing.JLabel txtEnvioDeUsuario;
    private javax.swing.JTextField txtModificarApellido1;
    private javax.swing.JTextField txtModificarDireccion1;
    private javax.swing.JTextField txtModificarDni1;
    private javax.swing.JTextField txtModificarLocalidad1;
    private javax.swing.JTextField txtModificarNombre1;
    private javax.swing.JTextField txtPantallaDeContactos;
    private javax.swing.JTextField txtPantallaDeContactos3;
    // End of variables declaration//GEN-END:variables
}
